version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: francesco
      POSTGRES_PASSWORD: fra
      POSTGRES_DB: PV
    ports:
      - "5434:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U francesco -d PV || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_server
    environment:
      DB_HOST: db
      DB_USER: francesco
      DB_PASSWORD: fra
      DB_NAME: PV
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app_server
    ports:
      - "3000:3000"
    command: npm run dev