services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: francesco
      POSTGRES_PASSWORD: fra
      POSTGRES_DB: PV
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U francesco -d PV || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_server
    environment:
      DB_HOST: db
      DB_USER: francesco
      DB_PASSWORD: fra
      DB_NAME: PV
      DB_PORT: 5432
      ENCRYPTION_KEY: "12345678901234567890123456789012" # 32 bytes
      IV: "1234567890123456" # 16 bytes
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app_server
    ports:
      - "3000:3000"
    command: sh -c "npm install tw-animate-css && npm run dev"
    volumes:
      - ./app:/usr/src/app
volumes:
  postgres_data: