import type { Metadata } from "next";
import "./globals.css";
import Sidebar from './components/sidebar'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return(
      <div className="h-[100vh] w-[100vw] overflow-hidden flex flex-row bg-white">
        <Sidebar/>
        <div className="h-full w-full pl-[20rem]" >
          {children}
        </div>
      </div>
  );
}
